# Arreglo Unidimensional de 6 elementos
ARREGLO_PRO1 = ["CARLOS ALBERTO", "BECERRA TERAN", "27", "DELGADILLO Y OLMEDO", "0923552567", "FUTBOL"] #INDICE 5
NOMBRE=ARREGLO_PRO1[0]
APELLIDOS=ARREGLO_PRO1[1]
CELULAR=ARREGLO_PRO1[4]
DIRECCION=ARREGLO_PRO1[3]
EDAD=ARREGLO_PRO1[2]
DEPORTE=ARREGLO_PRO1[5]

print (NOMBRE, APELLIDOS, CELULAR, DIRECCION, EDAD, DEPORTE)

# Reemplazar un valor en el arreglo
ARREGLO_PRO1[2]=30
EDAD=ARREGLO_PRO1[2]
print (NOMBRE, APELLIDOS, CELULAR, DIRECCION, EDAD, DEPORTE)

# Arreglo bidimensional 2x3
ARREGLO_PRO2=[
    [3,2,1], #INDICE 0
    [6,5,4] #INDICE 1
]
VALOR=ARREGLO_PRO2[0][2] #EXTRAER DATOS
print (VALOR)

# CAMBIAR 1 POR 30
ARREGLO_PRO2[0][2]=30 #ASIGNAR DATOS
VALOR=ARREGLO_PRO2[0][2]
print (VALOR)